// src/test_definition.rs
use serde::{Deserialize, Serialize};

/// Defines a test case, typically generated by the fuzzer or a test generator.
///
/// This structure decouples the definition of the mathematical function
/// from the code that computes it (the RPN evaluator).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestDefinition {
    /// A human-readable identifier for the test case.
    pub name: String,
    
    /// A brief description of the test case or how it was generated.
    pub description: String,
    
    /// The Reverse Polish Notation (RPN) tokens defining the mathematical expression.
    pub expression_rpn: Vec<String>,
    
    /// The number of inputs the expression expects.
    pub num_inputs: usize,
    
    /// The number of outputs the expression produces (typically 1).
    pub num_outputs: usize,
}